=== LibChecker/LibChecker-Rules/schemas/library-v5.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "library-v5",
  "type": "object",
  "properties": {
    "schemaVersion": {
      "const": 5
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
    },
    "iconId": {
      "type": [
        "string",
        "null"
      ]
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "locale": {
            "type": "string",
            "minLength": 1
          },
          "data": {
            "type": "object"
          }
        },
        "required": [
          "locale",
          "data"
        ],
        "additionalProperties": true
      }
    },
    "matchers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1,
            "maximum": 2147483647
          },
          "type": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          },
          "mode": {
            "enum": [
              "exact",
              "regex"
            ]
          },
          "priority": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2147483647
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "iconId": {
            "type": [
              "string",
              "null"
            ]
          },
          "regexName": {
            "type": [
              "string",
              "null"
            ]
          },
          "hasDetail": {
            "type": "boolean"
          },
          "legacyPath": {
            "type": [
              "string",
              "null"
            ]
          },
          "examples": {
            "type": "object",
            "properties": {
              "positive": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "negative": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "positive",
              "negative"
            ],
            "additionalProperties": false
          },
          "detailData": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "locale": {
                  "type": "string",
                  "minLength": 1
                },
                "data": {
                  "type": "object"
                }
              },
              "required": [
                "locale",
                "data"
              ],
              "additionalProperties": true
            }
          }
        },
        "required": [
          "id",
          "type",
          "name",
          "mode",
          "priority",
          "label",
          "iconId",
          "regexName",
          "hasDetail",
          "legacyPath",
          "examples"
        ],
        "additionalProperties": true
      }
    },
    "unreferencedDescriptions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "payload": {
            "type": "object",
            "properties": {
              "uuid": {
                "type": "string",
                "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "locale": {
                      "type": "string",
                      "minLength": 1
                    },
                    "data": {
                      "type": "object"
                    }
                  },
                  "required": [
                    "locale",
                    "data"
                  ],
                  "additionalProperties": true
                }
              }
            },
            "required": [
              "uuid",
              "data"
            ],
            "additionalProperties": true
          }
        },
        "required": [
          "path",
          "payload"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "schemaVersion",
    "uuid",
    "iconId",
    "data",
    "matchers",
    "unreferencedDescriptions"
  ],
  "additionalProperties": true
}

=== LibChecker/LibChecker-Rules/libraries/F7EDEC1B-0583-40E8-87B2-0F36CF2FB2AE.json
{
  "schemaVersion": 5,
  "uuid": "F7EDEC1B-0583-40E8-87B2-0F36CF2FB2AE",
  "iconId": "ic_lib_tencent_tds",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "Hippy",
        "dev_team": "TDS 腾讯端服务",
        "rule_contributors": [
          "Absinthe",
          "ArthurCyy",
          "ArcticFoxPro"
        ],
        "description": "Hippy 是 TDF 腾讯端框架（Tencent Device-oriented Framework）下的开源跨平台应用开发解决方案。Hippy 从底层做了大量工作，抹平了 iOS、Android、OpenHarmony 三端差异，提供了接近 Web 的开发体验，目前上层支持了 React 和 Vue 两套界面框架，前端开发人员可以通过它，将前端代码转换为终端的原生指令，进行原生终端 APP 的开发。同时，Hippy 从底层进行了大量优化，在启动速度、渲染性能、动画速度、内存占用、包体积等方面都提供了业内顶尖的性能表现。",
        "source_link": "https://github.com/Tencent/Hippy"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "Hippy",
        "dev_team": "Tencent Device-oriented Service",
        "rule_contributors": [
          "Absinthe",
          "ArthurCyy",
          "ArcticFoxPro"
        ],
        "description": "Hippy is a cross-platform development framework, that aims to help developers write once, and run on multiple platforms(iOS, Android, Web, and so on). Hippy is quite friendly to Web developers, especially those who are familiar with React or Vue.",
        "source_link": "https://github.com/Tencent/Hippy"
      }
    }
  ],
  "matchers": [
    {
      "id": 162,
      "type": 0,
      "name": "libhippybridge.so",
      "mode": "exact",
      "priority": 162,
      "label": "Hippy",
      "iconId": "ic_lib_tencent_tds",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libhippybridge.so.json",
      "examples": {
        "positive": [
          "libhippybridge.so"
        ],
        "negative": []
      }
    },
    {
      "id": 1342,
      "type": 0,
      "name": "libhippy.so",
      "mode": "exact",
      "priority": 1342,
      "label": "Hippy",
      "iconId": "ic_lib_tencent_tds",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libhippy.so.json",
      "examples": {
        "positive": [
          "libhippy.so"
        ],
        "negative": []
      }
    },
    {
      "id": 2026,
      "type": 0,
      "name": "libhippycanvas.so",
      "mode": "exact",
      "priority": 2026,
      "label": "Hippy",
      "iconId": "ic_lib_tencent_tds",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libhippycanvas.so.json",
      "examples": {
        "positive": [
          "libhippycanvas.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/DFD88136-D867-5C6B-AE03-6D5417EF73C1.json
{
  "schemaVersion": 5,
  "uuid": "DFD88136-D867-5C6B-AE03-6D5417EF73C1",
  "iconId": "ic_lib_iqiyi",
  "data": [],
  "matchers": [
    {
      "id": 879,
      "type": 2,
      "name": "org.qiyi.pluginlibrary.component.ServiceProxy3",
      "mode": "exact",
      "priority": 879,
      "label": "Neptune",
      "iconId": "ic_lib_iqiyi",
      "regexName": null,
      "hasDetail": false,
      "legacyPath": null,
      "examples": {
        "positive": [
          "org.qiyi.pluginlibrary.component.ServiceProxy3"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/80788713-184B-4E23-9DEE-E69EF570BBDA.json
{
  "schemaVersion": 5,
  "uuid": "80788713-184B-4E23-9DEE-E69EF570BBDA",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "libARMavlink",
        "dev_team": "Parrot",
        "rule_contributors": [
          "EntertainmentOne"
        ],
        "description": "在源代码和二进制形式下进行再分发和使用，允许修改与否，前提是满足以下条件：源代码的再分发必须保留上述版权声明、条件列表和以下免责声明。二进制形式的再分发必须在文档和/或其他分发材料中复制上述版权声明、条件列表和免责声明。未经事先书面许可，不得使用 Parrot 或其贡献者的名称来支持或推广基于此软件的衍生产品。",
        "source_link": "https://github.com/Parrot-Developers/libARMavlink"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "libARMavlink",
        "dev_team": "Parrot",
        "rule_contributors": [
          "EntertainmentOne"
        ],
        "description": "Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of Parrot nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.",
        "source_link": "https://github.com/Parrot-Developers/libARMavlink"
      }
    }
  ],
  "matchers": [
    {
      "id": 2108,
      "type": 0,
      "name": "libarmavlink.so",
      "mode": "exact",
      "priority": 2108,
      "label": "libARMavlink",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libarmavlink.so.json",
      "examples": {
        "positive": [
          "libarmavlink.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/73B6B0AF-A961-40A7-AAE0-8F0CB218DD9A.json
{
  "schemaVersion": 5,
  "uuid": "73B6B0AF-A961-40A7-AAE0-8F0CB218DD9A",
  "iconId": "ic_lib_google",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "WebM VP8/VP9",
        "dev_team": "Google",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "libvpx 是 Google 和开放媒体联盟 (AOMedia) 的一个免费软件视频编解码库。它作为 VP8 和 VP9 视频编码格式的参考软件实现，而对于 AV1，则有一个名为 libaom 的特殊分支，剥离了向后兼容性。",
        "source_link": "https://chromium.googlesource.com/webm/libvpx"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "WebM VP8/VP9",
        "dev_team": "Google",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "libvpx is a free software video codec library from Google and the Alliance for Open Media (AOMedia). It serves as the reference software implementation for the VP8 and VP9 video coding formats, and for AV1 a special fork named libaom that was stripped of backward compatibility.",
        "source_link": "https://chromium.googlesource.com/webm/libvpx"
      }
    }
  ],
  "matchers": [
    {
      "id": 1683,
      "type": 0,
      "name": "libvpx.so",
      "mode": "exact",
      "priority": 1683,
      "label": "WebM VP8/VP9",
      "iconId": "ic_lib_google",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libvpx.so.json",
      "examples": {
        "positive": [
          "libvpx.so"
        ],
        "negative": []
      }
    },
    {
      "id": 1684,
      "type": 0,
      "name": "libvpxV2JNI.so",
      "mode": "exact",
      "priority": 1684,
      "label": "WebM VP8/VP9",
      "iconId": "ic_lib_google",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libvpxV2JNI.so.json",
      "examples": {
        "positive": [
          "libvpxV2JNI.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/BA7BB8EE-5B00-4444-AEC3-3D011D7B6FD1.json
{
  "schemaVersion": 5,
  "uuid": "BA7BB8EE-5B00-4444-AEC3-3D011D7B6FD1",
  "iconId": "ic_lib_android",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "RenderScript Intrinsics Replacement Toolkit",
        "dev_team": "Android",
        "rule_contributors": [
          "ArthurCyy"
        ],
        "description": "此工具包提供了一组高性能的图像处理功能，如模糊、混合和调整大小。它可以作为大多数已弃用的 RenderScript Intrinsics 函数的独立替代品使用。",
        "source_link": "https://github.com/android/renderscript-intrinsics-replacement-toolkit"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "RenderScript Intrinsics Replacement Toolkit",
        "dev_team": "Android",
        "rule_contributors": [
          "ArthurCyy"
        ],
        "description": "This Toolkit provides a collection of high-performance image manipulation functions like blur, blend, and resize. It can be used as a stand-alone replacement for most of the deprecated RenderScript Intrinsics functions.",
        "source_link": "https://github.com/android/renderscript-intrinsics-replacement-toolkit"
      }
    }
  ],
  "matchers": [
    {
      "id": 1957,
      "type": 0,
      "name": "librenderscript-toolkit.so",
      "mode": "exact",
      "priority": 1957,
      "label": "RIRT",
      "iconId": "ic_lib_android",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/librenderscript-toolkit.so.json",
      "examples": {
        "positive": [
          "librenderscript-toolkit.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/7B1DA564-ADCF-437B-891E-203CBFF847BE.json
{
  "schemaVersion": 5,
  "uuid": "7B1DA564-ADCF-437B-891E-203CBFF847BE",
  "iconId": "ic_lib_android",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "File Provider",
        "dev_team": "Android",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "FileProvider 是 ContentProvider 的特殊子类，它通过创建 content://Uri 代替 file:///Uri 以促进安全分享与应用程序关联的文件。",
        "source_link": "https://developer.android.com/reference/androidx/core/content/FileProvider/"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "File Provider",
        "dev_team": "Android",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "FileProvider is a special subclass of ContentProvider that facilitates secure sharing of files associated with an application by creating content://Uri instead of file:///Uri.",
        "source_link": "https://developer.android.com/reference/androidx/core/content/FileProvider/"
      }
    }
  ],
  "matchers": [
    {
      "id": 433,
      "type": 4,
      "name": "android.support.v4.content.FileProvider",
      "mode": "exact",
      "priority": 433,
      "label": "File Provider",
      "iconId": "ic_lib_android",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "providers-libs/android/support/v4/content/FileProvider.json",
      "examples": {
        "positive": [
          "android.support.v4.content.FileProvider"
        ],
        "negative": []
      }
    },
    {
      "id": 449,
      "type": 4,
      "name": "androidx.core.content.FileProvider",
      "mode": "exact",
      "priority": 449,
      "label": "File Provider",
      "iconId": "ic_lib_android",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "providers-libs/androidx/core/content/FileProvider.json",
      "examples": {
        "positive": [
          "androidx.core.content.FileProvider"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/962AD26B-75B7-47EE-99FE-C617AF4ED6A8.json
{
  "schemaVersion": 5,
  "uuid": "962AD26B-75B7-47EE-99FE-C617AF4ED6A8",
  "iconId": "ic_lib_react",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "react-native-blob-util",
        "dev_team": "Ron Radtke",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "一个致力于让 React Native 开发者更轻松、更高效地进行文件访问和数据传输的项目。",
        "source_link": "https://github.com/RonRadtke/react-native-blob-util"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "react-native-blob-util",
        "dev_team": "Ron Radtke",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "A project committed to making file access and data transfer easier, efficient for React Native developers.",
        "source_link": "https://github.com/RonRadtke/react-native-blob-util"
      }
    }
  ],
  "matchers": [
    {
      "id": 2849,
      "type": 4,
      "name": "com.ReactNativeBlobUtil.Utils.FileProvider",
      "mode": "exact",
      "priority": 2849,
      "label": "react-native-blob-util",
      "iconId": "ic_lib_react",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "providers-libs/com/ReactNativeBlobUtil/Utils/FileProvider.json",
      "examples": {
        "positive": [
          "com.ReactNativeBlobUtil.Utils.FileProvider"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/FA8C2355-2037-5F07-8D77-F2B9EEF71A0A.json
{
  "schemaVersion": 5,
  "uuid": "FA8C2355-2037-5F07-8D77-F2B9EEF71A0A",
  "iconId": "ic_lib_jetpack",
  "data": [],
  "matchers": [
    {
      "id": 493,
      "type": 5,
      "name": "androidx.media",
      "mode": "exact",
      "priority": 493,
      "label": "Jetpack Media",
      "iconId": "ic_lib_jetpack",
      "regexName": null,
      "hasDetail": false,
      "legacyPath": null,
      "examples": {
        "positive": [
          "androidx.media"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}
