=== LibChecker/LibChecker-Rules/schemas/library-v5.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "library-v5",
  "type": "object",
  "properties": {
    "schemaVersion": {
      "const": 5
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
    },
    "iconId": {
      "type": [
        "string",
        "null"
      ]
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "locale": {
            "type": "string",
            "minLength": 1
          },
          "data": {
            "type": "object"
          }
        },
        "required": [
          "locale",
          "data"
        ],
        "additionalProperties": true
      }
    },
    "matchers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1,
            "maximum": 2147483647
          },
          "type": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          },
          "mode": {
            "enum": [
              "exact",
              "regex"
            ]
          },
          "priority": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2147483647
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "iconId": {
            "type": [
              "string",
              "null"
            ]
          },
          "regexName": {
            "type": [
              "string",
              "null"
            ]
          },
          "hasDetail": {
            "type": "boolean"
          },
          "legacyPath": {
            "type": [
              "string",
              "null"
            ]
          },
          "examples": {
            "type": "object",
            "properties": {
              "positive": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "negative": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "positive",
              "negative"
            ],
            "additionalProperties": false
          },
          "detailData": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "locale": {
                  "type": "string",
                  "minLength": 1
                },
                "data": {
                  "type": "object"
                }
              },
              "required": [
                "locale",
                "data"
              ],
              "additionalProperties": true
            }
          }
        },
        "required": [
          "id",
          "type",
          "name",
          "mode",
          "priority",
          "label",
          "iconId",
          "regexName",
          "hasDetail",
          "legacyPath",
          "examples"
        ],
        "additionalProperties": true
      }
    },
    "unreferencedDescriptions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "payload": {
            "type": "object",
            "properties": {
              "uuid": {
                "type": "string",
                "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "locale": {
                      "type": "string",
                      "minLength": 1
                    },
                    "data": {
                      "type": "object"
                    }
                  },
                  "required": [
                    "locale",
                    "data"
                  ],
                  "additionalProperties": true
                }
              }
            },
            "required": [
              "uuid",
              "data"
            ],
            "additionalProperties": true
          }
        },
        "required": [
          "path",
          "payload"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "schemaVersion",
    "uuid",
    "iconId",
    "data",
    "matchers",
    "unreferencedDescriptions"
  ],
  "additionalProperties": true
}

=== LibChecker/LibChecker-Rules/libraries/8597D3CF-C63E-42D4-ACAB-C74D68D33091.json
{
  "schemaVersion": 5,
  "uuid": "8597D3CF-C63E-42D4-ACAB-C74D68D33091",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "zipw",
        "dev_team": "A dog's life software",
        "rule_contributors": [
          "yfdyh000"
        ],
        "description": "一个共享库，适用于 Android、iOS*、OSX、Windows、Linux 和 webGL**，用于压缩/解压缩 zip/gzip/tar/bz2 (.zip/.gz) 文件和缓冲区。",
        "source_link": "https://assetstore.unity.com/packages/tools/input-management/zip-gzip-multiplatform-native-plugin-39411"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "zipw",
        "dev_team": "A dog's life software",
        "rule_contributors": [
          "yfdyh000"
        ],
        "description": "A shared library for Android, iOS*, OSX, Windows, Linux, and webGL** to compress/decompress zip/gzip/tar/bz2 (.zip/.gz) files and buffers.",
        "source_link": "https://assetstore.unity.com/packages/tools/input-management/zip-gzip-multiplatform-native-plugin-39411"
      }
    }
  ],
  "matchers": [
    {
      "id": 1204,
      "type": 0,
      "name": "libzipw.so",
      "mode": "exact",
      "priority": 1204,
      "label": "zipw",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libzipw.so.json",
      "examples": {
        "positive": [
          "libzipw.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/5D68FADA-9577-4DF6-BB72-8E4BCC72F0A4.json
{
  "schemaVersion": 5,
  "uuid": "5D68FADA-9577-4DF6-BB72-8E4BCC72F0A4",
  "iconId": "ic_lib_umeng",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "U-Share 社会化分享",
        "dev_team": "Umeng",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "帮助应用或游戏快速具备国内外多平台分享、第三方登录功能，SDK 包小，集成成本低，平台覆盖全。",
        "source_link": "https://www.umeng.com/social"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "U-Share Social Sharing",
        "dev_team": "Umeng",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "Helps applications or games quickly have multi-platform sharing and third-party login functions domestically and internationally. The SDK package is small, integration costs are low, and platform coverage is complete.",
        "source_link": "https://www.umeng.com/social"
      }
    }
  ],
  "matchers": [
    {
      "id": 353,
      "type": 2,
      "name": "com.umeng.socialize.media.WBShareCallBackActivity",
      "mode": "exact",
      "priority": 353,
      "label": "U-Share",
      "iconId": "ic_lib_umeng",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "activities-libs/com/umeng/socialize/media/WBShareCallBackActivity.json",
      "examples": {
        "positive": [
          "com.umeng.socialize.media.WBShareCallBackActivity"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/5EC1D41C-F0E8-4DAA-BCDC-A07452514D9D.json
{
  "schemaVersion": 5,
  "uuid": "5EC1D41C-F0E8-4DAA-BCDC-A07452514D9D",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "vad",
        "dev_team": "思必驰科技股份有限公司",
        "rule_contributors": [
          "WOLFRAZOR"
        ],
        "description": "DUI 致力于构建以场景服务为基础，针对智能家居、车载、机 器人、微信、客服、APP 等泛物联网领域，以用户为中心的自由人机交互系统，支持自由调用图文、列表、音乐、内嵌网页等多种控件，提供从唤醒、语音识别、 语义理解到对话管理、内容输出、TTS 播报的全链路技术的超高度定制；基于“云+端”的整体实现方案和完整的开发者服务，以对话（Dialog）为核心，从语音语言技术到对话管理、技能服务、交互界面均可以定制，VUI（Voice User Interface 语音用户界面）和 GUI（Graphical User Interface 图形用户界面）的相辅相成，完成“语音+触控”的完美结合。 众所周知，整个语音交互过程涉及从声音采集、前端信号处理、语音唤醒、语音识别、语义理解、智能对话、资源调用、回复内容生成、动作执行、合成音播报的主要环节，DUI系统支持整个全链路的语音技术使用，也支持其中某个或某几个环节，如语音唤醒、语音识别的单独使用或一两个联合使用。",
        "source_link": "https://www.duiopen.com/docs/ct_introduction"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "vad",
        "dev_team": "思必驰科技股份有限公司",
        "rule_contributors": [
          "WOLFRAZOR"
        ],
        "description": "DUI is dedicated to building a user-centered free human-machine interaction system based on scene services, targeting the smart home, in-vehicle, robotics, WeChat, customer service, app, and other IoT fields. It supports the free invocation of various controls such as images, lists, music, and embedded web pages, providing highly customizable full-link technology from wake-up, voice recognition, semantic understanding to dialogue management, content output, and TTS broadcasting. Based on the 'cloud + end' overall implementation plan and comprehensive developer services, with dialogue (Dialog) as the core, it allows customization from voice language technology to dialogue management, skill services, and interactive interfaces. The complementary relationship between VUI (Voice User Interface) and GUI (Graphical User Interface) achieves a perfect combination of 'voice + touch'. It is well known that the entire voice interaction process involves major stages from sound acquisition, front-end signal processing, voice wake-up, voice recognition, semantic understanding, intelligent dialogue, resource invocation, reply content generation, action execution, to synthesized voice broadcasting. The DUI system supports the use of the entire full-link voice technology, as well as the independent use of certain stages such as voice wake-up or voice recognition, or the combined use of one or two stages.",
        "source_link": "https://www.duiopen.com/docs/ct_introduction"
      }
    }
  ],
  "matchers": [
    {
      "id": 1961,
      "type": 0,
      "name": "libvad.so",
      "mode": "exact",
      "priority": 1961,
      "label": "vad",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libvad.so.json",
      "examples": {
        "positive": [
          "libvad.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/C2D10BC6-8853-4253-B993-DB51861AC085.json
{
  "schemaVersion": 5,
  "uuid": "C2D10BC6-8853-4253-B993-DB51861AC085",
  "iconId": "ic_lib_aliyun",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "阿里云短视频 SDK",
        "dev_team": "Alibaba",
        "rule_contributors": [
          "yfdyh000"
        ],
        "description": "阿里云短视频 SDK 依赖的第三方库。",
        "source_link": "https://help.aliyun.com/document_detail/94451.html"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "Alibaba Cloud Short Video SDK",
        "dev_team": "Alibaba",
        "rule_contributors": [
          "yfdyh000"
        ],
        "description": "Alibaba Cloud Short Video SDK relies on third-party libraries.",
        "source_link": "https://help.aliyun.com/document_detail/94451.html"
      }
    }
  ],
  "matchers": [
    {
      "id": 1224,
      "type": 0,
      "name": "libalivcffmpeg.so",
      "mode": "exact",
      "priority": 1224,
      "label": "阿里云短视频 SDK",
      "iconId": "ic_lib_aliyun",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libalivcffmpeg.so.json",
      "examples": {
        "positive": [
          "libalivcffmpeg.so"
        ],
        "negative": []
      }
    },
    {
      "id": 1225,
      "type": 0,
      "name": "libaliresample.so",
      "mode": "exact",
      "priority": 1225,
      "label": "阿里云短视频 SDK",
      "iconId": "ic_lib_aliyun",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libaliresample.so.json",
      "examples": {
        "positive": [
          "libaliresample.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/CA6A8B37-6359-4E6B-AE7B-B4439579BAB4.json
{
  "schemaVersion": 5,
  "uuid": "CA6A8B37-6359-4E6B-AE7B-B4439579BAB4",
  "iconId": "ic_lib_evernote",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "Android-Job",
        "dev_team": "evernote",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "Android 实用程序库，用于在后台延迟运行作业。 根据 Android 版本的不同，将使用 JobScheduler，GcmNetworkManager 或 AlarmManager。",
        "source_link": "https://github.com/evernote/android-job"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "Android-Job",
        "dev_team": "evernote",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "Android utility library for running jobs in the background with delay. Depending on the Android version, JobScheduler, GcmNetworkManager, or AlarmManager will be used.",
        "source_link": "https://github.com/evernote/android-job"
      }
    }
  ],
  "matchers": [
    {
      "id": 200,
      "type": 1,
      "name": "com.evernote.android.job.JobRescheduleService",
      "mode": "exact",
      "priority": 200,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "services-libs/com/evernote/android/job/JobRescheduleService.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.JobRescheduleService"
        ],
        "negative": []
      }
    },
    {
      "id": 221,
      "type": 1,
      "name": "com.evernote.android.job.v14.PlatformAlarmService",
      "mode": "exact",
      "priority": 221,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "services-libs/com/evernote/android/job/v14/PlatformAlarmService.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.v14.PlatformAlarmService"
        ],
        "negative": []
      }
    },
    {
      "id": 222,
      "type": 1,
      "name": "com.evernote.android.job.v21.PlatformJobService",
      "mode": "exact",
      "priority": 222,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "services-libs/com/evernote/android/job/v21/PlatformJobService.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.v21.PlatformJobService"
        ],
        "negative": []
      }
    },
    {
      "id": 228,
      "type": 1,
      "name": "com.evernote.android.job.v14.PlatformAlarmServiceExact",
      "mode": "exact",
      "priority": 228,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "services-libs/com/evernote/android/job/v14/PlatformAlarmServiceExact.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.v14.PlatformAlarmServiceExact"
        ],
        "negative": []
      }
    },
    {
      "id": 384,
      "type": 3,
      "name": "com.evernote.android.job.v14.PlatformAlarmReceiver",
      "mode": "exact",
      "priority": 384,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "receivers-libs/com/evernote/android/job/v14/PlatformAlarmReceiver.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.v14.PlatformAlarmReceiver"
        ],
        "negative": []
      }
    },
    {
      "id": 389,
      "type": 3,
      "name": "com.evernote.android.job.JobBootReceiver",
      "mode": "exact",
      "priority": 389,
      "label": "Android-Job",
      "iconId": "ic_lib_evernote",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "receivers-libs/com/evernote/android/job/JobBootReceiver.json",
      "examples": {
        "positive": [
          "com.evernote.android.job.JobBootReceiver"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/B7766B8D-76C4-567A-9AA9-B93180648C2A.json
{
  "schemaVersion": 5,
  "uuid": "B7766B8D-76C4-567A-9AA9-B93180648C2A",
  "iconId": "ic_lib_jetpack",
  "data": [],
  "matchers": [
    {
      "id": 501,
      "type": 5,
      "name": "androidx.collection",
      "mode": "exact",
      "priority": 501,
      "label": "Jetpack Collection",
      "iconId": "ic_lib_jetpack",
      "regexName": null,
      "hasDetail": false,
      "legacyPath": null,
      "examples": {
        "positive": [
          "androidx.collection"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/4B7C950F-66AA-459A-8AAF-F4F5FE19085E.json
{
  "schemaVersion": 5,
  "uuid": "4B7C950F-66AA-459A-8AAF-F4F5FE19085E",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "dotLottie Android",
        "dev_team": "LottieFiles",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "用于 Android 的 dotLottie 动画播放器。",
        "source_link": "https://github.com/LottieFiles/dotlottie-android"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "dotLottie Android",
        "dev_team": "LottieFiles",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "dotLottie animation player for Android.",
        "source_link": "https://github.com/LottieFiles/dotlottie-android"
      }
    }
  ],
  "matchers": [
    {
      "id": 2943,
      "type": 0,
      "name": "libdlplayer.so",
      "mode": "exact",
      "priority": 2943,
      "label": "dotLottie Android",
      "iconId": "ic_lib_dotlottie",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libdlplayer.so.json",
      "examples": {
        "positive": [
          "libdlplayer.so"
        ],
        "negative": []
      }
    },
    {
      "id": 2944,
      "type": 0,
      "name": "libdotlottie_player.so",
      "mode": "exact",
      "priority": 2944,
      "label": "dotLottie Android",
      "iconId": "ic_lib_dotlottie",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libdotlottie_player.so.json",
      "examples": {
        "positive": [
          "libdotlottie_player.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/2686F06A-BFC3-415D-83BA-AC3E31C579D5.json
{
  "schemaVersion": 5,
  "uuid": "2686F06A-BFC3-415D-83BA-AC3E31C579D5",
  "iconId": "ic_lib_tencent",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "王卡 SDK",
        "dev_team": "Tencent",
        "rule_contributors": [
          "Absinthe",
          "yfdyh000"
        ],
        "description": "本组件用于识别当前用户使用的上网卡是否为王卡。识别后给王卡用户以相应的免流状态提示和王卡身份感知。",
        "source_link": "http://tengxundldocument.gcloud.qq.com/pages/documents/details.html?projectId=204"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "KingCard SDK",
        "dev_team": "Tencent",
        "rule_contributors": [
          "Absinthe",
          "yfdyh000"
        ],
        "description": "This component is used to identify whether the current user's SIM card is a KingCard. Once identified, KingCard users will receive the corresponding free data usage status prompt and KingCard identity awareness.",
        "source_link": "http://tengxundldocument.gcloud.qq.com/pages/documents/details.html?projectId=204"
      }
    }
  ],
  "matchers": [
    {
      "id": 2517,
      "type": 0,
      "name": "libKcsdk-2.0.9",
      "mode": "exact",
      "priority": 2517,
      "label": "王卡 SDK",
      "iconId": "ic_lib_tencent",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libKcsdk-2.0.9.json",
      "examples": {
        "positive": [
          "libKcsdk-2.0.9"
        ],
        "negative": []
      }
    },
    {
      "id": 2573,
      "type": 1,
      "name": "tmsdk.common.KcBaseService",
      "mode": "exact",
      "priority": 2573,
      "label": "王卡 SDK",
      "iconId": "ic_lib_tencent",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "services-libs/tmsdk/common/KcBaseService.json",
      "examples": {
        "positive": [
          "tmsdk.common.KcBaseService"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": [
    {
      "path": "actions-libs/com.tencent.kingcard.calibration.json",
      "payload": {
        "data": [
          {
            "locale": "zh-Hans",
            "data": {
              "label": "王卡 SDK",
              "dev_team": "Tencent",
              "rule_contributors": [
                "Absinthe",
                "yfdyh000"
              ],
              "description": "本组件用于识别当前用户使用的上网卡是否为王卡。识别后给王卡用户以相应的免流状态提示和王卡身份感知。",
              "source_link": "http://tengxundldocument.gcloud.qq.com/pages/documents/details.html?projectId=204"
            }
          },
          {
            "locale": "en",
            "data": {
              "label": "KingCard SDK",
              "dev_team": "Tencent",
              "rule_contributors": [
                "Absinthe",
                "yfdyh000"
              ],
              "description": "This component is used to identify whether the current user's SIM card is a KingCard. Once identified, KingCard users will receive the corresponding free data usage status prompt and KingCard identity awareness.",
              "source_link": "http://tengxundldocument.gcloud.qq.com/pages/documents/details.html?projectId=204"
            }
          }
        ],
        "uuid": "2686F06A-BFC3-415D-83BA-AC3E31C579D5"
      }
    }
  ]
}
