=== LibChecker/LibChecker-Rules/schemas/library-v5.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "library-v5",
  "type": "object",
  "properties": {
    "schemaVersion": {
      "const": 5
    },
    "uuid": {
      "type": "string",
      "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
    },
    "iconId": {
      "type": [
        "string",
        "null"
      ]
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "locale": {
            "type": "string",
            "minLength": 1
          },
          "data": {
            "type": "object"
          }
        },
        "required": [
          "locale",
          "data"
        ],
        "additionalProperties": true
      }
    },
    "matchers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1,
            "maximum": 2147483647
          },
          "type": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          },
          "mode": {
            "enum": [
              "exact",
              "regex"
            ]
          },
          "priority": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2147483647
          },
          "label": {
            "type": "string",
            "minLength": 1
          },
          "iconId": {
            "type": [
              "string",
              "null"
            ]
          },
          "regexName": {
            "type": [
              "string",
              "null"
            ]
          },
          "hasDetail": {
            "type": "boolean"
          },
          "legacyPath": {
            "type": [
              "string",
              "null"
            ]
          },
          "examples": {
            "type": "object",
            "properties": {
              "positive": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "negative": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "positive",
              "negative"
            ],
            "additionalProperties": false
          },
          "detailData": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "locale": {
                  "type": "string",
                  "minLength": 1
                },
                "data": {
                  "type": "object"
                }
              },
              "required": [
                "locale",
                "data"
              ],
              "additionalProperties": true
            }
          }
        },
        "required": [
          "id",
          "type",
          "name",
          "mode",
          "priority",
          "label",
          "iconId",
          "regexName",
          "hasDetail",
          "legacyPath",
          "examples"
        ],
        "additionalProperties": true
      }
    },
    "unreferencedDescriptions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string"
          },
          "payload": {
            "type": "object",
            "properties": {
              "uuid": {
                "type": "string",
                "pattern": "^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$"
              },
              "data": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "locale": {
                      "type": "string",
                      "minLength": 1
                    },
                    "data": {
                      "type": "object"
                    }
                  },
                  "required": [
                    "locale",
                    "data"
                  ],
                  "additionalProperties": true
                }
              }
            },
            "required": [
              "uuid",
              "data"
            ],
            "additionalProperties": true
          }
        },
        "required": [
          "path",
          "payload"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "schemaVersion",
    "uuid",
    "iconId",
    "data",
    "matchers",
    "unreferencedDescriptions"
  ],
  "additionalProperties": true
}

=== LibChecker/LibChecker-Rules/libraries/E43C0CDE-82F3-4A7A-BE14-0F71DBEC3D4E.json
{
  "schemaVersion": 5,
  "uuid": "E43C0CDE-82F3-4A7A-BE14-0F71DBEC3D4E",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "翼支付",
        "dev_team": "China Telecom",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "翼支付是天翼电子商务有限公司旗下品牌，覆盖餐饮娱乐、交通出行、电商购物、民生缴费、通信交费等多个生活消费场景的便民服务。",
        "source_link": "https://www.bestpay.com.cn/"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "YiPay",
        "dev_team": "China Telecom",
        "rule_contributors": [
          "Absinthe"
        ],
        "description": "Yi Payment is a brand under Tianyi E-Commerce Co., Ltd., covering various life consumption scenarios such as catering and entertainment, transportation, e-commerce shopping, utility bill payment, and communication fee payment.",
        "source_link": "https://www.bestpay.com.cn/"
      }
    }
  ],
  "matchers": [
    {
      "id": 339,
      "type": 2,
      "name": "com.bestpay.app.H5PayActivity",
      "mode": "exact",
      "priority": 339,
      "label": "翼支付",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "activities-libs/com/bestpay/app/H5PayActivity.json",
      "examples": {
        "positive": [
          "com.bestpay.app.H5PayActivity"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/64AC0E1B-61B2-5EBE-B06F-09B1A48CDA92.json
{
  "schemaVersion": 5,
  "uuid": "64AC0E1B-61B2-5EBE-B06F-09B1A48CDA92",
  "iconId": "ic_lib_fresco",
  "data": [],
  "matchers": [
    {
      "id": 528,
      "type": 5,
      "name": "com.facebook.fresco",
      "mode": "exact",
      "priority": 528,
      "label": "Fresco",
      "iconId": "ic_lib_fresco",
      "regexName": null,
      "hasDetail": false,
      "legacyPath": null,
      "examples": {
        "positive": [
          "com.facebook.fresco"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/03E0B89A-55F3-480E-9DDF-87EF69ADDA5C.json
{
  "schemaVersion": 5,
  "uuid": "03E0B89A-55F3-480E-9DDF-87EF69ADDA5C",
  "iconId": "ic_lib_tencent_cloud",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "腾讯云 HTTPDNS",
        "dev_team": "Tencent",
        "rule_contributors": [
          "su1216",
          "crrashh1542"
        ],
        "description": "HTTPDNS 基于 HTTP 协议向腾讯云的 DNS 服务器发送域名解析请求，替代了基于 DNS 协议向运营商 LocalDNS 发起解析请求的传统方式，可以避免 LocalDNS 造成的域名劫持和跨网访问问题，解决移动互联网服务中域名解析异常带来的困扰。",
        "source_link": "https://github.com/tencentyun/httpdns-android-sdk"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "Tencent Cloud HTTPDNS",
        "dev_team": "Tencent",
        "rule_contributors": [
          "su1216",
          "crrashh1542"
        ],
        "description": "HTTPDNS sends domain name resolution requests to Tencent Cloud's DNS server based on the HTTP protocol, replacing the traditional method of initiating resolution requests to the operator's LocalDNS based on the DNS protocol. This can avoid domain hijacking and cross-network access issues caused by LocalDNS, solving the troubles brought by domain resolution anomalies in mobile internet services.",
        "source_link": "https://github.com/tencentyun/httpdns-android-sdk"
      }
    }
  ],
  "matchers": [
    {
      "id": 32,
      "type": 0,
      "name": "libhttpdns.so",
      "mode": "exact",
      "priority": 32,
      "label": "腾讯云 HTTPDNS",
      "iconId": "ic_lib_tencent_cloud",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libhttpdns.so.json",
      "examples": {
        "positive": [
          "libhttpdns.so"
        ],
        "negative": []
      }
    },
    {
      "id": 2515,
      "type": 0,
      "name": "libHttpDnsCore.so",
      "mode": "exact",
      "priority": 2515,
      "label": "腾讯云 HTTPDNS",
      "iconId": "ic_lib_tencent_cloud",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libHttpDnsCore.so.json",
      "examples": {
        "positive": [
          "libHttpDnsCore.so"
        ],
        "negative": []
      }
    },
    {
      "id": 2516,
      "type": 0,
      "name": "libHttpDnsPlugin.so",
      "mode": "exact",
      "priority": 2516,
      "label": "腾讯云 HTTPDNS",
      "iconId": "ic_lib_tencent_cloud",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libHttpDnsPlugin.so.json",
      "examples": {
        "positive": [
          "libHttpDnsPlugin.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/145D0BA4-8D0F-465E-BF0E-197F699EA4B6.json
{
  "schemaVersion": 5,
  "uuid": "145D0BA4-8D0F-465E-BF0E-197F699EA4B6",
  "iconId": "ic_lib_callstack_media_kit",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "React Native Slider",
        "dev_team": "Callstack",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "一个 React Native 组件，分别封装了 iOS 的 Slider 和 Android 的 SeekBar。",
        "source_link": "https://github.com/callstack/react-native-slider"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "React Native Slider",
        "dev_team": "Callstack",
        "rule_contributors": [
          "sebastien46"
        ],
        "description": "React Native component exposing Slider from iOS and SeekBar from Android.",
        "source_link": "https://github.com/callstack/react-native-slider"
      }
    }
  ],
  "matchers": [
    {
      "id": 2659,
      "type": 0,
      "name": "libreact_codegen_RNCSlider.so",
      "mode": "exact",
      "priority": 2659,
      "label": "React Native Slider",
      "iconId": "ic_lib_callstack_media_kit",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libreact_codegen_RNCSlider.so.json",
      "examples": {
        "positive": [
          "libreact_codegen_RNCSlider.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/3A2D8C47-1A1B-45B4-9F73-5FD53AA5D807.json
{
  "schemaVersion": 5,
  "uuid": "3A2D8C47-1A1B-45B4-9F73-5FD53AA5D807",
  "iconId": "ic_lib_microsoft",
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "1DS",
        "dev_team": "Microsoft",
        "rule_contributors": [
          "binx6"
        ],
        "description": "1DS (One Data Strategy，亦称为 One Observability) C/C++ SDK 使得从各种微软产品收集跨平台遥测数据成为可能。它支持将数据/遥测上传到 Collector++。",
        "source_link": "https://github.com/microsoft/cpp_client_telemetry"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "1DS",
        "dev_team": "Microsoft",
        "rule_contributors": [
          "binx6"
        ],
        "description": "1DS (One Data Strategy, also known as One Observability) C/C++ SDK enables cross-platform telemetry collection from various Microsoft products. It enables data / telemetry upload to Collector++.",
        "source_link": "https://github.com/microsoft/cpp_client_telemetry"
      }
    }
  ],
  "matchers": [
    {
      "id": 2229,
      "type": 0,
      "name": "libmaesdk.so",
      "mode": "exact",
      "priority": 2229,
      "label": "1DS",
      "iconId": "ic_lib_microsoft",
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libmaesdk.so.json",
      "examples": {
        "positive": [
          "libmaesdk.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/72387397-E1AF-47DC-8855-C876D8FBB668.json
{
  "schemaVersion": 5,
  "uuid": "72387397-E1AF-47DC-8855-C876D8FBB668",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "react-native-mmkv",
        "dev_team": "margelo",
        "rule_contributors": [
          "coder-xiaomo",
          "crrashh1542"
        ],
        "description": "react-native-mmkv 是一个库，可让你通过到原生 C++ 库的快速直接 JS 绑定，在 React Native 应用中轻松使用 MMKV。",
        "source_link": "https://github.com/margelo/react-native-mmkv"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "react-native-mmkv",
        "dev_team": "margelo",
        "rule_contributors": [
          "coder-xiaomo",
          "crrashh1542"
        ],
        "description": "react-native-mmkv is a library that allows you to easily use MMKV inside your React Native app through fast and direct JS bindings to the native C++ library.",
        "source_link": "https://github.com/margelo/react-native-mmkv"
      }
    }
  ],
  "matchers": [
    {
      "id": 2767,
      "type": 0,
      "name": "libNitroMmkv.so",
      "mode": "exact",
      "priority": 2767,
      "label": "react-native-mmkv",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libNitroMmkv.so.json",
      "examples": {
        "positive": [
          "libNitroMmkv.so"
        ],
        "negative": []
      }
    },
    {
      "id": 2932,
      "type": 0,
      "name": "libreactnativemmkv.so",
      "mode": "exact",
      "priority": 2932,
      "label": "react-native-mmkv",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libreactnativemmkv.so.json",
      "examples": {
        "positive": [
          "libreactnativemmkv.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/F81DC466-2845-422B-AD4F-29ED68FF6B61.json
{
  "schemaVersion": 5,
  "uuid": "F81DC466-2845-422B-AD4F-29ED68FF6B61",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "AntiFakerAndroidChecker",
        "dev_team": "happylishang",
        "rule_contributors": [
          "ArthurCyy"
        ],
        "description": "Android 模拟器检测，检测 Android 模拟器，作为可信 DeviceID，应对防刷需求等。",
        "source_link": "https://github.com/happylishang/AntiFakerAndroidChecker"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "AntiFakerAndroidChecker",
        "dev_team": "happylishang",
        "rule_contributors": [
          "ArthurCyy"
        ],
        "description": "Android emulator detection, detecting Android emulators, serving as a trusted DeviceID, addressing anti-brushing needs, etc.",
        "source_link": "https://github.com/happylishang/AntiFakerAndroidChecker"
      }
    }
  ],
  "matchers": [
    {
      "id": 1338,
      "type": 0,
      "name": "libemulator_check.so",
      "mode": "exact",
      "priority": 1338,
      "label": "AntiFakerAndroidChecker",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libemulator_check.so.json",
      "examples": {
        "positive": [
          "libemulator_check.so"
        ],
        "negative": []
      }
    },
    {
      "id": 1339,
      "type": 0,
      "name": "libproperty_get.so",
      "mode": "exact",
      "priority": 1339,
      "label": "AntiFakerAndroidChecker",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/libproperty_get.so.json",
      "examples": {
        "positive": [
          "libproperty_get.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}

=== LibChecker/LibChecker-Rules/libraries/321F7C3B-21A5-47AE-9D1E-20EFB840224B.json
{
  "schemaVersion": 5,
  "uuid": "321F7C3B-21A5-47AE-9D1E-20EFB840224B",
  "iconId": null,
  "data": [
    {
      "locale": "zh-Hans",
      "data": {
        "label": "Foxit PDF SDK",
        "dev_team": "Foxit",
        "rule_contributors": [
          "binx6"
        ],
        "description": "Foxit PDF SDK for Android 致力于帮助开发人员快速将强大的 Foxit PDF 技术集成到他们自己的移动端应用程序中。通过 Foxit 开发包，即使是对 PDF 了解有限的开发人员也可以在 Android 平台上用几行代码快速构建一个专业的 PDF 阅读器。有关更多详细信息，可以访问网站https://developers.foxitsoftware.cn/pdf-sdk/。",
        "source_link": "https://developers.foxit.com/"
      }
    },
    {
      "locale": "en",
      "data": {
        "label": "Foxit PDF SDK",
        "dev_team": "Foxit",
        "rule_contributors": [
          "binx6"
        ],
        "description": "Foxit PDF SDK for Android aims to help developers quickly integrate powerful Foxit PDF technology into their own mobile applications. With the Foxit development kit, even developers with limited PDF knowledge can quickly build a professional PDF reader on the Android platform with just a few lines of code. For more details, you can visit the website https://developers.foxitsoftware.cn/pdf-sdk/.",
        "source_link": "https://developers.foxit.com/"
      }
    }
  ],
  "matchers": [
    {
      "id": 1611,
      "type": 0,
      "name": "librdk.so",
      "mode": "exact",
      "priority": 1611,
      "label": "Foxit PDF SDK",
      "iconId": null,
      "regexName": null,
      "hasDetail": true,
      "legacyPath": "native-libs/librdk.so.json",
      "examples": {
        "positive": [
          "librdk.so"
        ],
        "negative": []
      }
    }
  ],
  "unreferencedDescriptions": []
}
